POST http://localhost:3000/toDo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pY29sYXNNYXJ0aW4iLCJpZCI6IjY0NGVhOWYyNTQ1ZjgyYzY5YWQzOWE3YSIsImlhdCI6MTY4MjkzNjk2NCwiZXhwIjoxNjgzNTQxNzY0fQ.h_61kBXD4_KXdk1ziPpkRMJIQmW30nAxC40wpdnmhTA
Content-Type: application/json

{
    "title": "de apoco",
    "completed": "true"
}