GET http://localhost:3000/togglecompleted/644fc692046cd4447a9db7d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pY29sYXNNYXJ0aW4iLCJpZCI6IjY0NGVhOWYyNTQ1ZjgyYzY5YWQzOWE3YSIsImlhdCI6MTY4Mjk1MTM4OSwiZXhwIjoxNjgzNTU2MTg5fQ.EUnkAYuoubtfKktRtr6segzHKgpi18gHCvHRfbJrTao